module.exports = [
    {
        inputs: [
            { internalType: "string", name: "_poolName", type: "string" },
            {
                internalType: "string",
                name: "_brandName",
                type: "string",
            },
            {
                internalType: "uint256",
                name: "_capital",
                type: "uint256",
            },
            {
                internalType: "address",
                name: "_capitalAddress",
                type: "address",
            },
            {
                internalType: "address",
                name: "_nftAddress",
                type: "address",
            },
            {
                internalType: "address",
                name: "_poolOwner",
                type: "address",
            },
            { internalType: "address", name: "_rng", type: "address" },
            {
                internalType: "uint256",
                name: "_campaignLength",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "_votingLength",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "_decisionLength",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "_submissionLength",
                type: "uint256",
            },
        ],
        stateMutability: "nonpayable",
        type: "constructor",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "address",
                name: "PoolAddress",
                type: "address",
            },
            {
                indexed: false,
                internalType: "string",
                name: "PoolName",
                type: "string",
            },
            {
                indexed: false,
                internalType: "string",
                name: "BrandName",
                type: "string",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "SubmissionNumber",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "address",
                name: "Caller",
                type: "address",
            },
        ],
        name: "CashedOut",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "address",
                name: "PoolAddress",
                type: "address",
            },
            {
                indexed: false,
                internalType: "string",
                name: "PoolName",
                type: "string",
            },
            {
                indexed: false,
                internalType: "string",
                name: "BrandName",
                type: "string",
            },
            {
                indexed: false,
                internalType: "uint256[10]",
                name: "TopTen",
                type: "uint256[10]",
            },
        ],
        name: "NewTopTen",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "address",
                name: "PoolAddress",
                type: "address",
            },
            {
                indexed: false,
                internalType: "string",
                name: "PoolName",
                type: "string",
            },
            {
                indexed: false,
                internalType: "string",
                name: "BrandName",
                type: "string",
            },
            {
                indexed: false,
                internalType: "bool",
                name: "BackedByFunds",
                type: "bool",
            },
        ],
        name: "PoolBacked",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "address",
                name: "PoolAddress",
                type: "address",
            },
            {
                indexed: false,
                internalType: "string",
                name: "PoolName",
                type: "string",
            },
            {
                indexed: false,
                internalType: "string",
                name: "BrandName",
                type: "string",
            },
        ],
        name: "PoolNameChanged",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "address",
                name: "PoolAddress",
                type: "address",
            },
            {
                indexed: false,
                internalType: "string",
                name: "PoolName",
                type: "string",
            },
            {
                indexed: false,
                internalType: "string",
                name: "BrandName",
                type: "string",
            },
            {
                indexed: false,
                internalType: "uint256[]",
                name: "Finalists",
                type: "uint256[]",
            },
        ],
        name: "SeeFinalists",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "address",
                name: "PoolAddress",
                type: "address",
            },
            {
                indexed: false,
                internalType: "string",
                name: "PoolName",
                type: "string",
            },
            {
                indexed: false,
                internalType: "string",
                name: "BrandName",
                type: "string",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "SubmissionNumber",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "address",
                name: "ArtistAddress",
                type: "address",
            },
            {
                indexed: false,
                internalType: "uint256[3]",
                name: "NFTsInSubmission",
                type: "uint256[3]",
            },
        ],
        name: "SubmissionCreated",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "address",
                name: "PoolAddress",
                type: "address",
            },
            {
                indexed: false,
                internalType: "string",
                name: "PoolName",
                type: "string",
            },
            {
                indexed: false,
                internalType: "string",
                name: "BrandName",
                type: "string",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "SubmissionNumber",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "address",
                name: "Voter",
                type: "address",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "NewVoteCount",
                type: "uint256",
            },
        ],
        name: "VoteSubmitted",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "address",
                name: "PoolAddress",
                type: "address",
            },
            {
                indexed: false,
                internalType: "string",
                name: "PoolName",
                type: "string",
            },
            {
                indexed: false,
                internalType: "string",
                name: "BrandName",
                type: "string",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "Winner",
                type: "uint256",
            },
        ],
        name: "WinnerSelected",
        type: "event",
    },
    {
        inputs: [],
        name: "backPool",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [],
        name: "backedByFunds",
        outputs: [{ internalType: "bool", name: "", type: "bool" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "brandName",
        outputs: [{ internalType: "string", name: "", type: "string" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "brandVotingEndTime",
        outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "campaignEndTime",
        outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "_submissionNumber",
                type: "uint256",
            },
        ],
        name: "cashout",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [{ internalType: "string", name: "_name", type: "string" }],
        name: "changeName",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [],
        name: "checkForTies",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256[3]",
                name: "nfts",
                type: "uint256[3]",
            },
        ],
        name: "createSubmission",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "_submissionNumber",
                type: "uint256",
            },
        ],
        name: "fanVote",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [],
        name: "fanVotingEndTime",
        outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "funds",
        outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "getName",
        outputs: [{ internalType: "string", name: "", type: "string" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "getTopTen",
        outputs: [
            { internalType: "uint256[10]", name: "", type: "uint256[10]" },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "getTopTenAmount",
        outputs: [
            { internalType: "uint256[10]", name: "", type: "uint256[10]" },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "getfinalists",
        outputs: [{ internalType: "uint256[]", name: "", type: "uint256[]" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "getfinalistsAmount",
        outputs: [{ internalType: "uint256[]", name: "", type: "uint256[]" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "poolName",
        outputs: [{ internalType: "string", name: "", type: "string" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "poolOwner",
        outputs: [{ internalType: "address", name: "", type: "address" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "seePoolBacking",
        outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "submissionIndex",
                type: "uint256",
            },
        ],
        name: "selectWinner",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [],
        name: "submissionEndTime",
        outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        name: "submissions",
        outputs: [
            {
                internalType: "uint256",
                name: "userCount",
                type: "uint256",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        name: "topTen",
        outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        name: "topTenAmount",
        outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "topTenFound",
        outputs: [{ internalType: "bool", name: "", type: "bool" }],
        stateMutability: "view",
        type: "function",
    },
];
